### ISSUE TITLE
Create a beautiful and responsive homepage

### ISSUE THREAD

**Issue by sandessth** [sandessth/e-commerce-app#6]

**Comment by sandessth** [comment]
Design an attractive homepage with appealing visuals, user-friendly navigation, and responsive layout for various devices.

Estimated Days: 2 days

**Comment by sandessth** [comment]
Home Page

![Image](https://github.com/sandessth/e-commerce-app/assets/133729653/58c93ea9-4a42-49b1-a7f7-2aebfb098a01)

**Comment by yogeshtakeo** [comment]
Design is beautiful 😻
