### ISSUE TITLE
Implement user authentication and authorization

### ISSUE THREAD

**Issue by sandessth** [sandessth/e-commerce-app#8]

**Comment by sandessth** [comment]
Develop a secure login and registration system to protect user data and manage access to specific features.

estimated days: 2 days

**Comment by yogeshtakeo** [comment]
I need the screenshots though 😊

**Comment by sandessth** [comment]
![Image](https://github.com/sandessth/e-commerce-app/assets/133729653/4d5d3eb3-1b74-4fa8-845a-7e90da5a737b)



![Image](https://github.com/sandessth/e-commerce-app/assets/133729653/03761072-8230-4b4c-b10e-c1976d7dd101)

**Comment by yogeshtakeo** [comment]
i am excited for the demontration for this. ☺️
